---
- name: Prelim Exam
  hosts: all




  tasks:
    - name: config.yaml
      include_vars:
        file: config.yaml




- name: Roles
  hosts: all
  roles:
     - python_install
     - java_install
     - motd
     - usr
